import express from "express";
import cors from "cors";
import path from "path";
import { authRouter } from "@/routes/auth.routes";
import { vehiclesRouter } from "@/routes/vehicles.routes";
import { serviceOrdersRouter } from "@/routes/service-orders.routes";
import { timelineRouter } from "@/routes/timeline.routes";
import { partsRouter } from "@/routes/parts.routes";
import { approvalsRouter } from "@/routes/approvals.routes";
import { chatRouter } from "@/routes/chat.routes";
import { uploadsRouter } from "@/routes/uploads.routes";
import { quoteRequestsRouter } from "@/routes/quote-requests.routes";
import { inventoryPartsRouter } from "@/routes/inventory-parts.routes";
import { financeRouter } from "@/routes/finance.routes";
import { bankAccountsRouter } from "@/routes/bank-accounts.routes";
import { accountsPayableRouter } from "@/routes/accounts-payable.routes";
import { accountsReceivableRouter } from "@/routes/accounts-receivable.routes";
import { invoicesRouter } from "@/routes/invoices.routes";
import { suppliersRouter } from "@/routes/suppliers.routes";
import { purchaseOrdersRouter } from "@/routes/purchase-orders.routes";
import { baysRouter } from "@/routes/bays.routes";
import { appointmentsRouter } from "@/routes/appointments.routes";
import { clientsRouter } from "@/routes/clients.routes";
import { rolesRouter, permissionsRouter } from "@/routes/roles.routes";
import { counterSalesRouter } from "@/routes/counter-sales.routes";
import { reportsRouter } from "@/routes/reports.routes";
import { partWarrantyRouter, warrantiesReportRouter } from "@/routes/warranties.routes";
import { commissionsRouter } from "@/routes/commissions.routes";
import { storesRouter } from "@/routes/stores.routes";
import { insuranceCompaniesRouter } from "@/routes/insurance-companies.routes";
import { sectorsRouter } from "@/routes/sectors.routes";
import { serviceCatalogRouter } from "@/routes/service-catalog.routes";
import { estimatesRouter } from "@/routes/estimates.routes";
import { supplementsRouter } from "@/routes/supplements.routes";
import { inspectionsRouter } from "@/routes/inspections.routes";
import { vehicleDamagesRouter } from "@/routes/vehicle-damages.routes";
import { timeEntriesRouter } from "@/routes/time-entries.routes";
import { auditRouter } from "@/routes/audit.routes";
import { alertsRouter } from "@/routes/alerts.routes";
import { documentTemplatesRouter } from "@/routes/document-templates.routes";
import { searchRouter } from "@/routes/search.routes";

export const app = express();

app.use(cors({ origin: process.env.CORS_ORIGIN || "http://localhost:3000" }));
app.use(express.json());
app.use("/uploads", express.static(path.resolve(process.cwd(), process.env.UPLOADS_DIR || "uploads")));

app.get("/health", (_req, res) => res.json({ ok: true, service: "box-backend" }));

app.use("/api/auth", authRouter);
app.use("/api/vehicles", vehiclesRouter);
app.use("/api/service-orders", serviceOrdersRouter);
app.use("/api/service-orders/:orderId/timeline", timelineRouter);
app.use("/api/service-orders/:orderId/parts", partsRouter);
app.use("/api/service-orders/:orderId/parts", partWarrantyRouter);
app.use("/api/service-orders/:orderId/approvals", approvalsRouter);
app.use("/api/service-orders/:orderId/chat", chatRouter);
app.use("/api/service-orders/:orderId/damages", vehicleDamagesRouter);
app.use("/api/uploads", uploadsRouter);
app.use("/api/quote-requests", quoteRequestsRouter);
app.use("/api/inventory-parts", inventoryPartsRouter);
app.use("/api/finance/bank-accounts", bankAccountsRouter);
app.use("/api/finance/payables", accountsPayableRouter);
app.use("/api/finance/receivables", accountsReceivableRouter);
app.use("/api/finance", financeRouter);
app.use("/api/invoices", invoicesRouter);
app.use("/api/suppliers", suppliersRouter);
app.use("/api/purchase-orders", purchaseOrdersRouter);
app.use("/api/agenda/bays", baysRouter);
app.use("/api/agenda/appointments", appointmentsRouter);
app.use("/api/clients", clientsRouter);
app.use("/api/roles", rolesRouter);
app.use("/api/permissions", permissionsRouter);
app.use("/api/counter-sales", counterSalesRouter);
app.use("/api/reports", reportsRouter);
app.use("/api/warranties", warrantiesReportRouter);
app.use("/api/commissions", commissionsRouter);
app.use("/api/stores", storesRouter);
app.use("/api/insurance-companies", insuranceCompaniesRouter);
app.use("/api/sectors", sectorsRouter);
app.use("/api/service-catalog", serviceCatalogRouter);
app.use("/api/estimates", estimatesRouter);
app.use("/api/supplements", supplementsRouter);
app.use("/api/inspections", inspectionsRouter);
app.use("/api/time-entries", timeEntriesRouter);
app.use("/api/audit-logs", auditRouter);
app.use("/api/alerts", alertsRouter);
app.use("/api/document-templates", documentTemplatesRouter);
app.use("/api/search", searchRouter);

app.use((_req, res) => res.status(404).json({ error: "Rota não encontrada." }));
